### PR TITLE
Save to disk broken after resource split

### LINKED ISSUE #5: Memory file broken, no metadata
Ever since the change that split the metadata from the embeddings, it can't be loaded from disk anymore, as only the embeddings get saved an not the metadata.

This makes everything work just fine when using it from Ram, but completely breaks as soon as you try to load from storage.

Not sure what is a clean solution here, as saving two files would also be a hassle...

We could make a single dictionary outa the two of them when saving and splitting again once loaded?

### PR DESCRIPTION
**Pull request by AWAS666**
fixes #5 

As the storage currently takes a list of dicts I did it on an index basis, might be cleaner to change the storage to take a dictionary instead.

### CODE REVIEW

**Comment by vprelovac** [comment]
Dict does seem to be cleaner and more future proof to allow adding/omittin other elements, can you change?

**Comment by AWAS666** [comment]
I aggree but will have to wait till tomorrow.

**Comment by AWAS666** [comment]
The in-between solution, doesn't change the storage, but uses a dictionary.

**Comment by vprelovac** [comment]
Excellent, thanks!

**Pull request merged**
